MODEL:
  FREEZE_AT: 4
  CLASSES: 100
INPUT:
  DATASET: 'cifar100'
  DATASET_ROOT: '/media/willer/data/DataSet/cifar100/'
  MEAN: [0.50707516, 0.48654887, 0.44091784]
  STD: [0.26733429, 0.25643846, 0.27615047]
TRAIN:
  BATCH_SIZE: 128
  EPOCH: 10
  CHECK_PERIOD: 1
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MILESTONES: [3, 8]
  GAMMA: 0.1
TEST:
  BATCH_SIZE: 128
OUTPUT_DIR: 'CIFAR100/'
