MODEL:
  FREEZE_AT: 1
  CLASSES: 10
INPUT:
  DATASET: 'cifar10'
  DATASET_ROOT: '/media/ubuntu/76c3afb9-9877-4540-ac95-6a70ac97a8fc/DataSets/cifar10/'
  MEAN: [0.49139968, 0.48215841, 0.44653091]
  STD: [0.24703223, 0.24348513, 0.26158784]
TRAIN:
  BATCH_SIZE: 64
  EPOCH: 20
  CHECK_PERIOD: 1
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MILESTONES: [4, 14]
  GAMMA: 0.1
TEST:
  BATCH_SIZE: 64
OUTPUT_DIR: 'CIFAR10/'
