MODEL:
  FREEZE_AT: 1 
  CLASSES: 100
INPUT:
  DATASET: 'cifar100'
  DATASET_ROOT: '/media/ubuntu/76c3afb9-9877-4540-ac95-6a70ac97a8fc/DataSets/cifar100/'
  MEAN: [0.50707516, 0.48654887, 0.44091784]
  STD: [0.26733429, 0.25643846, 0.27615047]
TRAIN:
  BATCH_SIZE: 64
  EPOCH: 20
  CHECK_PERIOD: 1
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  MILESTONES: [4, 14]
  GAMMA: 0.1
TEST:
  BATCH_SIZE: 64
OUTPUT_DIR: 'CIFAR100/'
