MODEL:
  FREEZE_AT: 2
  CLASSES: 10
INPUT:
  DATASET: 'cifar10'
  DATASET_ROOT: '/media/willer/data/DataSet/cifar10/'
  MEAN: [0.49139968, 0.48215841, 0.44653091]
  STD: [0.24703223, 0.24348513, 0.26158784]
TRAIN:
  BATCH_SIZE: 128
  EPOCH: 10
  CHECK_PERIOD: 1
SOLVER:
  BASE_LR: 0.002
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MILESTONES: [3, 8]
  GAMMA: 0.1
TEST:
  BATCH_SIZE: 128
OUTPUT_DIR: 'CIFAR10/'
