import os
from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = 'cuda'
_C.MODEL.FREEZE_AT = 1
_C.MODEL.CLASSES = 0

_C.INPUT = CN()
_C.INPUT.DATASET = 'cifar10'
_C.INPUT.DATASET_ROOT = ''
_C.INPUT.MEAN = []
_C.INPUT.STD = []

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 4

_C.TRAIN = CN()
_C.TRAIN.BATCH_SIZE = 150
_C.TRAIN.EPOCH = 10
_C.TRAIN.CHECK_PERIOD = 1
_C.TRAIN.MAX_LEN = 10

_C.SOLVER = CN()
_C.SOLVER.BASE_LR = 0.1
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.GAMMA = 0.1
_C.SOLVER.MILESTONES = (3, 8)

_C.TEST = CN()
_C.TEST.BATCH_SIZE = 128

_C.OUTPUT_DIR = 'models/'